name: orm
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: any
  uuid: any
  mongo_dart: ^0.2.10
  connection_pool: ^0.1.2
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
